# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=128)),
                ('lname', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.UserCategory'),
        ),
    ]
